version: '3.8'
services:
  dev-db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
    networks:
      - freecodecamp

  test-db:
    image: postgres:14-alpine
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
    networks:
      - freecodecamp
networks:
  freecodecamp:
